'use strict';
angular.module('codecentricers')

.constant('version', {
  revision: '',
  flavor: 'develop',
  built: 'Tue Jul 12 2016 12:03:05',
  version: '1.0.1',
  license: 'MIT'
})

.constant('globals', {
  baseUrl: 'https://api.github.com',
  apiToken: '',
  apiVersion: '1',
  apiTimeout: 10000,
  pollingDelay: 30000,
  maxStartTime: 120000,
  localStorageKey: 'codecentricers',
  debug: true,
  keepMessages: 20,
  customer:{
    title: 'Codecentricers',
    longtitle: 'Codecentricers - Codecentric Developers',
    name: 'generic',
    domain: 'codecentricers.com',
  },
  menuNav: {
    main: ['home', 'contact'],
    // Content for subnav
    home: [],
    contact: [],
  },
  redirectOnLogin: '/',
  pLangs: [
    'Objective-C',
    'HTML',
    'Ruby',
    'Shell',
    'Swift',
    'Java',
    'C#',
    'Batchfile',
    'C',
    'C++',
    'Cpp',
    'Awk',
    'Groovy',
    'Groff',
    'CSS',
    'Makefile',
    'Scala',
    'Go',
    'TypeScript',
    'ASP',
    'Python',
    'JavaScript',
    'Lex',
    'Scheme',
    'Clojure',
    'Prolog',
    'CoffeeScript',
    'VimL',
    'FreeMarker',
    'Assembly',
    'XSLT',
    'R',
    'Cucumber',
    'TeX',
    'Thrift',
    'Inno Setup',
    'PHP',
    'ApacheConf',
    'Visual Basic',
    'Perl',
    'Protocol Buffer',
    'Emacs Lisp',
    'Puppet',
    'Arduino',
    'Rust',
    'Erlang',
    'Nu',
    'Smalltalk',
    'Lua',
    'AppleScript',
    'ActionScript',
    'Tcl',
    'SQLPL',
    'Smarty',
    'RobotFramework',
    'Elixir',
    'GCC Machine Description',
    'PostScript',
    'Diff'
  ]
});
